"use client";
import {useCallback,useEffect,useMemo,useState} from "react";
import {createClient} from "genlayer-js";
import {studioDevnet} from "genlayer-js/chains";
import {createTransactionKit} from "@genlayer/transaction-kit";
import {GenLayerTransactionPanel,type SubmitInput,type TrackedStatus} from "@genlayer/transaction-kit-react";
import {Braces,Check,ChevronRight,GitPullRequest,Plus,RefreshCw,ShieldCheck,X} from "lucide-react";

type Finding={index:number;state:"MET"|"PARTIAL"|"MISSED";source_indexes:number[];pinpoint_quote:string};
type Revision={id:string;case_id:string;patch_url:string;note:string;status:string;result:{overall?:string;findings?:Finding[];source_receipts?:{index:number;url:string;sha256:string}[]}};
type ReviewCase={id:string;title:string;owner:string;spec_url:string;criteria:string[];revision_ids:string[]};
type Mode="case"|"revision"|"inspect"|null;
const ADDRESS=process.env.NEXT_PUBLIC_CONTRACT_ADDRESS||""; const RPC=process.env.NEXT_PUBLIC_GENLAYER_RPC_URL||"https://studio-next.genlayer.com/api"; const CHAIN_ID=Number(process.env.NEXT_PUBLIC_GENLAYER_CHAIN_ID||"61997"); const CHAIN={...studioDevnet,id:CHAIN_ID,name:"GenLayer Studio Next",rpcUrls:{default:{http:[RPC]}}};
const SPEC="https://raw.githubusercontent.com/nearar22/threadmark/992484c4d145c4c0d3d82e94c248e097714637c6/README.md";
const PATCH="https://raw.githubusercontent.com/nearar22/threadmark/992484c4d145c4c0d3d82e94c248e097714637c6/contracts/threadmark.py";
function clean(v:any):any{if(v instanceof Map)return Object.fromEntries([...v.entries()].map(([k,x])=>[k,clean(x)]));if(Array.isArray(v))return v.map(clean);if(v&&typeof v==="object")return Object.fromEntries(Object.entries(v).map(([k,x])=>[k,clean(x)]));if(typeof v==="bigint")return Number(v);return v}
function tiny(v:string){return v.length>17?`${v.slice(0,9)}…${v.slice(-6)}`:v}

export default function Page(){
 const [caseId,setCaseId]=useState("author-safety-demo"),[title,setTitle]=useState("Author safety remediation"),[specUrl,setSpecUrl]=useState(SPEC),[criteriaText,setCriteriaText]=useState("Validate every author wallet before changing state.\nAllow only the board owner to manage authors.");
 const [reviewCase,setReviewCase]=useState<ReviewCase|null>(null),[revisions,setRevisions]=useState<Revision[]>([]),[selected,setSelected]=useState<string>(""),[revisionId,setRevisionId]=useState("revision-one"),[patchUrl,setPatchUrl]=useState(PATCH),[note,setNote]=useState("Implements strict wallet normalization and owner-only author management."),[wallet,setWallet]=useState<string|null>(null),[message,setMessage]=useState(""),[mode,setMode]=useState<Mode>(null),[activeTx,setActiveTx]=useState<Mode>(null),[loading,setLoading]=useState(false);
 const client=useMemo(()=>createClient({chain:CHAIN}),[]); const kit=useMemo(()=>wallet&&typeof window!=="undefined"&&(window as any).ethereum?createTransactionKit({chain:CHAIN,provider:(window as any).ethereum,account:wallet as `0x${string}`}):null,[wallet]);
 const refresh=useCallback(async()=>{if(!ADDRESS||!caseId.trim())return;setLoading(true);try{const c=clean(await client.readContract({address:ADDRESS as `0x${string}`,functionName:"get_case",args:[caseId.trim()]})) as ReviewCase;const rs=clean(await client.readContract({address:ADDRESS as `0x${string}`,functionName:"list_revisions",args:[caseId.trim()]})) as Revision[];setReviewCase(c);setRevisions(rs);setSelected(x=>x||rs.at(-1)?.id||"");setMessage("")}catch{setReviewCase(null);setRevisions([]);setMessage("No review case found at this ID yet.")}finally{setLoading(false)}},[caseId,client]); useEffect(()=>{void refresh()},[refresh]);
 const connect=async()=>{const p=(window as any).ethereum;if(!p){setMessage("Install MetaMask to write. Public review results remain readable without a wallet.");return}try{const accounts=await p.request({method:"eth_requestAccounts"});const hex=`0x${CHAIN_ID.toString(16)}`;if(Number.parseInt(await p.request({method:"eth_chainId"}),16)!==CHAIN_ID){try{await p.request({method:"wallet_switchEthereumChain",params:[{chainId:hex}]})}catch(e:any){if(e?.code!==4902)throw e;await p.request({method:"wallet_addEthereumChain",params:[{chainId:hex,chainName:"GenLayer Studio Next",rpcUrls:[RPC],nativeCurrency:{name:"GEN",symbol:"GEN",decimals:18}}]})}}setWallet(accounts[0]||null);setMessage("")}catch(e:any){setMessage(e?.message||"Wallet connection did not complete.")}};
 const criteria=criteriaText.split("\n").map(x=>x.trim()).filter(Boolean); const tx=useMemo<SubmitInput|null>(()=>{if(!ADDRESS||!activeTx)return null;const base={kind:"write" as const,address:ADDRESS as `0x${string}`};if(activeTx==="case")return{...base,method:"open_case",args:[caseId.trim(),title.trim(),specUrl.trim(),criteria]};if(activeTx==="revision")return{...base,method:"submit_revision",args:[caseId.trim(),revisionId.trim(),patchUrl.trim(),note.trim()]};return{...base,method:"inspect_revision",args:[caseId.trim(),selected]};},[activeTx,caseId,title,specUrl,criteria,revisionId,patchUrl,note,selected]);
 const done=(s:TrackedStatus)=>{if(s.phase!=="finalized")return;if(s.successful){setActiveTx(null);setMode(null);setMessage("");void refresh()}else{setActiveTx(null);setMessage(`Transaction failed: ${s.executionResultName||s.statusName||"contract rejected the input"}.`)}}; const submit=()=>{if(!kit){setMessage("Connect a Studio Next wallet before writing.");return}if(mode==="inspect"&&!selected){setMessage("Select a queued revision first.");return}setMessage("");setActiveTx(mode)}; const current=revisions.find(x=>x.id===selected)||null;
 return <main className="shell"><header><div className="wordmark"><span><Braces/></span><b>PATCHPROOF</b><small>SPEC-BOUND REVIEW</small></div><div className="net"><i/>STUDIO NEXT {CHAIN_ID}</div><button className="wallet" onClick={connect}>{wallet?tiny(wallet):"Connect wallet"}</button></header>
 <section className="command"><div><small>REVIEW CASE</small><label><input aria-label="Case ID" value={caseId} onChange={e=>setCaseId(e.target.value)}/><button onClick={()=>void refresh()} disabled={loading}><RefreshCw size={15}/>{loading?"Reading":"Load case"}</button></label></div><p>Ship against the written acceptance criteria, not a summary remembered after the fact.</p><div className="actions"><button onClick={()=>setMode("case")}><Plus size={16}/>New case</button><button onClick={()=>setMode("revision")} disabled={!reviewCase}><GitPullRequest size={16}/>Submit revision</button><button className="hot" onClick={()=>setMode("inspect")} disabled={!current||current.status!=="QUEUED"}><ShieldCheck size={16}/>Run jury</button></div></section>
 <section className="workbench"><aside><div className="aside-title"><span>REVISION STACK</span><b>{revisions.length}/5</b></div>{revisions.length?revisions.map((r,i)=><button key={r.id} className={selected===r.id?"active":""} onClick={()=>setSelected(r.id)}><span>{String(i+1).padStart(2,"0")}</span><div><b>{r.id}</b><small>{r.status}</small></div><ChevronRight size={16}/></button>):<div className="empty">No patches queued.<br/>Open a case, then submit an immutable implementation file.</div>}</aside>
 <article><div className="review-head"><div><small>{reviewCase?"ACTIVE DOSSIER":"EMPTY WORKBENCH"}</small><h1>{reviewCase?.title||"A patch earns its checkmarks."}</h1></div><span className={`verdict ${current?.status?.toLowerCase()||"queued"}`}>{current?.status||"WAITING"}</span></div><div className="spec-strip"><span>SPEC</span><a href={reviewCase?.spec_url||specUrl} target="_blank">{tiny(reviewCase?.spec_url||specUrl)}</a><code>{current?.result?.source_receipts?.[0]?.sha256?.slice(0,12)||"digest pending"}</code></div>
 <div className="rubric"><div className="rubric-head"><span>ACCEPTANCE CRITERIA</span><span>EVIDENCE RETURNED BY VALIDATORS</span></div>{(reviewCase?.criteria||criteria).map((criterion,i)=>{const f=current?.result?.findings?.find(x=>x.index===i);return <div className="criterion" key={i}><div className="criterion-name"><span>{f?.state==="MET"?<Check/>:i+1}</span><p>{criterion}</p></div><div className="evidence">{f?<><b className={f.state.toLowerCase()}>{f.state}</b><q>{f.pinpoint_quote}</q><small>SOURCE {f.source_indexes.join(", ")}</small></>:<em>Awaiting a finalized review</em>}</div></div>})}</div>{current&&<div className="patch-foot"><span>IMPLEMENTATION</span><a href={current.patch_url} target="_blank">{tiny(current.patch_url)}</a><p>{current.note}</p></div>}</article></section>
 {message&&<div className="toast">{message}<button onClick={()=>setMessage("")}><X size={14}/></button></div>}
 {mode&&<div className="modal"><section><button className="close" onClick={()=>setMode(null)}><X/></button><small>PATCHPROOF WRITE PATH</small><h2>{mode==="case"?"Open a review case":mode==="revision"?"Queue an immutable patch":"Ask the validator jury"}</h2>{mode==="case"&&<><label>CASE ID<input value={caseId} onChange={e=>setCaseId(e.target.value)}/></label><label>TITLE<input value={title} onChange={e=>setTitle(e.target.value)}/></label><label>PINNED SPEC URL<input value={specUrl} onChange={e=>setSpecUrl(e.target.value)}/></label><label>ONE CRITERION PER LINE<textarea value={criteriaText} onChange={e=>setCriteriaText(e.target.value)}/></label></>}{mode==="revision"&&<><label>REVISION ID<input value={revisionId} onChange={e=>setRevisionId(e.target.value)}/></label><label>PINNED IMPLEMENTATION URL<input value={patchUrl} onChange={e=>setPatchUrl(e.target.value)}/></label><label>CHANGE NOTE<textarea value={note} onChange={e=>setNote(e.target.value)}/></label></>}{mode==="inspect"&&<div className="confirm"><ShieldCheck/><p>Validators will independently fetch the pinned spec and patch, judge every criterion, and bind each finding to an exact quote.</p></div>}<button className="commit" onClick={submit}>{mode==="inspect"?"Start consensus review":"Continue to wallet"}</button><small className="finality">The workbench refreshes only after successful FINALIZED status.</small></section></div>}
 {activeTx&&tx&&kit&&<div className="modal"><section className="tx"><button className="close" onClick={()=>setActiveTx(null)}><X/></button><GenLayerTransactionPanel kit={kit} tx={tx} network="GenLayer Studio Next" theme="dark" trackUntil="finalized" onDone={done}/></section></div>}</main>}
